name: convex-coder

services:
  backend:
    image: convex-backend-s3-compatible:latest
    stop_grace_period: 10s
    stop_signal: SIGINT
    ports:
      - "${PORT:-3210}:3210"
      - "${SITE_PROXY_PORT:-3211}:3211"
    volumes:
      - data:/convex/data
    env_file:
      - .env.docker
    environment:
      - INSTANCE_NAME=${INSTANCE_NAME:-}
      - INSTANCE_SECRET=${INSTANCE_SECRET:-}
      - CONVEX_RELEASE_VERSION_DEV=${CONVEX_RELEASE_VERSION_DEV:-}
      - ACTIONS_USER_TIMEOUT_SECS=${ACTIONS_USER_TIMEOUT_SECS:-}
      - CONVEX_CLOUD_ORIGIN=${CONVEX_CLOUD_ORIGIN}
      - CONVEX_SITE_ORIGIN=${CONVEX_SITE_ORIGIN}
      - DATABASE_URL=${DATABASE_URL:-}
      - DISABLE_BEACON=${DISABLE_BEACON:-}
      - REDACT_LOGS_TO_CLIENT=${REDACT_LOGS_TO_CLIENT:-}
      - DO_NOT_REQUIRE_SSL=${DO_NOT_REQUIRE_SSL:-}
      - POSTGRES_URL=${POSTGRES_URL:-}
      - MYSQL_URL=${MYSQL_URL:-}
      - RUST_LOG=${RUST_LOG:-info}
      - RUST_BACKTRACE=${RUST_BACKTRACE:-}
      - LOG_FORMAT=${LOG_FORMAT:-}
      - NO_COLOR=${NO_COLOR:-}
      - CONVEX_TRACE_FILE=${CONVEX_TRACE_FILE:-}
      - CONVEX_SITE=${CONVEX_SITE:-}
      - ISOLATE_V8_FLAGS=${ISOLATE_V8_FLAGS:-}
      - CONVEX_DEPLOY_KEY=${CONVEX_DEPLOY_KEY:-}
      - AWS_S3_USE_PATH_STYLE_ACCESS=${AWS_S3_USE_PATH_STYLE_ACCESS:-}
      - AWS_S3_DISABLE_SSL=${AWS_S3_DISABLE_SSL:-}
      - S3_USE_ACCELERATE=${S3_USE_ACCELERATE:-}
    depends_on:
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3210/version"]
      interval: 3s
      timeout: 5s
      retries: 3
      start_period: 15s

  dashboard:
    image: ghcr.io/get-convex/convex-dashboard:33cef775a8a6228cbacee4a09ac2c4073d62ed13
    stop_grace_period: 10s
    stop_signal: SIGINT
    ports:
      - "${DASHBOARD_PORT:-6791}:6791"
    env_file:
      - .env.docker
    environment:
      - PORT=${DASHBOARD_PORT:-6791}
      - NEXT_PUBLIC_DEPLOYMENT_URL=${NEXT_PUBLIC_DEPLOYMENT_URL}
      - NEXT_PUBLIC_ADMIN_KEY=${NEXT_PUBLIC_ADMIN_KEY:-}
      - NEXT_PUBLIC_HIDE_HEADER=${NEXT_PUBLIC_HIDE_HEADER:-}
      - BUILD_TYPE=${BUILD_TYPE:-}
    depends_on:
      backend:
        condition: service_healthy

  # MinIO S3-compatible gateway
  minio:
    image: quay.io/minio/minio:latest
    command: server --console-address ":9001" --compat /data
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin123}
      - MINIO_OPTS=--compat
      - MINIO_KMS_AUTO_ENCRYPTION=off
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  data:
  minio_data:
